### ISSUE TITLE
UI displays different timezones in the job list and the execution history

### ISSUE THREAD

**Issue by alexanderfefelov** [distribworks/dkron#839] opened 2020-10-26 09:31 UTC
Dkron 3.0.5:

![1](https://user-images.githubusercontent.com/5790321/97155782-e9c52500-1786-11eb-988d-2cb03e4f46d6.png)

![2](https://user-images.githubusercontent.com/5790321/97155797-ecc01580-1786-11eb-8ada-a2397c04c3db.png)

**Comment by yvanoers** [comment] 2020-10-26 20:46
Looks like the same feature request as #526.

**Comment by victorcoder** [comment] 2020-11-05 16:29
Duplicate of #526

**Closed by victorcoder** 2020-11-05 16:29 UTC
Labels: duplicate, enhancement
