### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by clarifysky** [distribworks/dkron#794] opened 2020-06-29 02:35 UTC
**Describe the bug**
I have three nodes, after 5 days of running, one of them crashed.
Actually, even one node, after 5 days of running, it may also crash.

**To Reproduce**
1. Launch dkron: `nohup dkron agent >> /var/log/dkron.log &`.
2. Create several jobs (per second, per miniute, per hour, per day, many kinds).
3. Let it keep running for 5 days or more. 
4. After 5 days of running, watch the process of dkron (it may have crashed), then view the log.

**Expected behavior**
It can run steadily at least for about half of a month.

**Screenshots**

** Specifications:**
 - OS: linux
 - Version: 3.10.0

**Additional context**
Below is the crash log:

```log
time="2020-06-25T05:19:12+00:00" level=debug msg="dkron: shutting down leader loop" node=abc
time="2020-06-25T05:19:12+00:00" level=debug msg="scheduler: Stopping scheduler" node=abc
time="2020-06-25T05:19:12+00:00" level=info msg="2020-06-25T05:19:12.758+0000 [INFO]  raft: aborting pipeline replication: peer=\"{Voter abc01 192.168.10.1:6868}\""
time="2020-06-25T05:19:12+00:00" level=info msg="dkron: cluster leadership lost" node=abc
time="2020-06-25T05:19:12+00:00" level=info msg="dkron: monitoring leadership" node=abc
time="2020-06-25T05:19:12+00:00" level=info msg="2020-06-25T05:19:12.826+0000 [ERROR] raft: failed to appendEntries to: peer=\"{Voter abc02 192.168.10.2:6868}\" error=\"dial tcp 192.168.10.2:6868: i/o timeout\""
time="2020-06-25T05:19:14+00:00" level=info msg="2020-06-25T05:19:14.146+0000 [DEBUG] raft: lost leadership because received a requestVote with a newer term"
time="2020-06-25T05:19:14+00:00" level=info msg="2020-06-25T05:19:14.223+0000 [ERROR] raft: failed to heartbeat to: peer=192.168.10.2:6868 error=\"dial tcp 192.168.10.2:6868: i/o timeout\""
time="2020-06-25T05:19:17+00:00" level=debug msg="job: Run job" job=abc01_check_tomcat node=abc schedule="@every 1m"
time="2020-06-25T05:19:17+00:00" level=debug msg="store: Retrieved job from datastore" job=abc01_check_tomcat node=abc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xe10615]

goroutine 208067 [running]:
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:74
github.com/robfig/cron/v3.(*Cron).Entries(0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:178 +0x55
github.com/distribworks/dkron/v3/dkron.(*Scheduler).GetEntry(0xc0002ff260, 0xc0015490c0, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /GitHub/dkron/dkron/scheduler.go:82 +0x74
github.com/distribworks/dkron/v3/dkron.(*Agent).Run(0xc000d14000, 0xc0015490c0, 0x12, 0xc000f55f80, 0xc001980780, 0x2d3f336, 0x21)
        /GitHub/dkron/dkron/run.go:20 +0x8ae
github.com/distribworks/dkron/v3/dkron.(*Job).Run(0xc001980780)
        /GitHub/dkron/dkron/job.go:239 +0x2ba
github.com/robfig/cron/v3.(*Cron).startJob.func1(0xc000c0cc80, 0x36a4f20, 0xc001980780)
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x69
created by github.com/robfig/cron/v3.(*Cron).startJob
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x73
```

**Comment by clarifysky** [comment] 2020-06-29 02:52
```log
time="2020-06-18T18:37:28+00:00" level=info msg="agent: Calling AgentRun" job_name=abc01_obtain_apple node="192.168.10.1:6868"
time="2020-06-18T18:38:00+00:00" level=info msg="agent: Calling AgentRun" job_name=abc01_deliciously_suck node="192.168.10.1:6868"
time="2020-06-18T18:38:00+00:00" level=info msg="job: Skipping concurrent execution" concurrency=forbid job=abc01_darkest_vision job_status=success node=abc003
time="2020-06-18T18:38:00+00:00" level=info msg="agent: Calling AgentRun" job_name=abc_whispersob_crazily_grow node="192.168.10.3:6868"
time="2020-06-18T18:38:00+00:00" level=info msg="grpc_agent: Starting job" job=abc_whispersob_crazily_grow node=abc003
time="2020-06-18T18:38:00+00:00" level=info msg="agent: Calling AgentRun" job_name=abc_whispersob_deliciously_suck node="192.168.10.3:6868"
time="2020-06-18T18:38:00+00:00" level=info msg="grpc_agent: Starting job" job=abc_whispersob_deliciously_suck node=abc003
time="2020-06-18T18:38:01+00:00" level=info msg="agent: Calling AgentRun" job_name=abc_whispersob_saadlly_runn node="192.168.10.3:6868"
time="2020-06-18T18:38:01+00:00" level=info msg="grpc_agent: Starting job" job=abc_whispersob_saadlly_runn node=abc003
time="2020-06-18T18:38:30+00:00" level=info msg="agent: Calling AgentRun" job_name=abc002_job node="192.168.10.2:6868"
time="2020-06-18T18:38:30+00:00" level=info msg="agent: Calling AgentRun" job_name=abc01_obtain_apple node="192.168.10.1:6868"
time="2020-06-18T18:38:30+00:00" level=info msg="agent: Calling AgentRun" job_name=abc002_echo node="192.168.10.2:6868"
time="2020-06-18T18:39:00+00:00" level=info msg="dkron: cluster leadership lost" node=abc003
time="2020-06-18T18:39:00+00:00" level=info msg="dkron: monitoring leadership" node=abc003
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xe10615]

goroutine 421114 [running]:
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:74
github.com/robfig/cron/v3.(*Cron).Entries(0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:178 +0x55
github.com/distribworks/dkron/v3/dkron.(*Scheduler).GetEntry(0xc000bd0660, 0xc000f22620, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /GitHub/dkron/dkron/scheduler.go:82 +0x74
github.com/distribworks/dkron/v3/dkron.(*Agent).Run(0xc000cb8000, 0xc000f22620, 0x14, 0xc000188980, 0xc000e44f00, 0xc00028b901, 0x2c821a0)
        /GitHub/dkron/dkron/run.go:20 +0x8ae
github.com/distribworks/dkron/v3/dkron.(*Job).Run(0xc000e44f00)
        /GitHub/dkron/dkron/job.go:239 +0x2ba
github.com/robfig/cron/v3.(*Cron).startJob.func1(0xc00019b220, 0x36a4f20, 0xc000e44f00)
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x69
created by github.com/robfig/cron/v3.(*Cron).startJob
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x73
```

**Comment by clarifysky** [comment] 2020-07-10 06:59
I've submitted a PR which could solve this prblem, #799. Any advice ?

**Comment by victorcoder** [comment] 2020-07-10 11:05
I've never experienced this issue, been running Dkron clusters for months without a crash. Let me check the PR because I don't understand exactly what's going on.

**Comment by clarifysky** [comment] 2020-07-13 02:55
![nil cause crash](https://imgur.com/HWJ7NaY "nil cause crash")

May this graph can help.

**Comment by drauschenbach** [comment] 2020-07-22 16:21
I just experienced this again. My stack trace is slightly different (no mention of Mutex), here it is in case it helps:

```
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: 2020/07/22 03:30:14 [ERR] yamux: keepalive failed: write unix @->/tmp/plugin401067681: write: broken pipe
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: time="2020-07-22T03:30:14-07:00" level=info msg="dkron: cluster leadership lost" node=myhost006
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: time="2020-07-22T03:30:14-07:00" level=info msg="dkron: monitoring leadership" node=myhost006
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xdb6fe1]
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: goroutine 186454 [running]:
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: github.com/robfig/cron/v3.(*Cron).Entries(0x0, 0x0, 0x0, 0x0)
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:178 +0x51
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: github.com/distribworks/dkron/v3/dkron.(*Scheduler).GetEntry(0xc00011db80, 0xc002f82940, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: /go/pkg/mod/github.com/distribworks/dkron/v3@v3.0.4/dkron/scheduler.go:82 +0x74
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: github.com/distribworks/dkron/v3/dkron.(*Agent).Run(0xc000d7e140, 0xc002f82940, 0x1b, 0xc003720e80, 0xc0034ad980, 0x16, 0x2a31e00)
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: /go/pkg/mod/github.com/distribworks/dkron/v3@v3.0.4/dkron/run.go:20 +0x8a6
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: github.com/distribworks/dkron/v3/dkron.(*Job).Run(0xc0034ad980)
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: /go/pkg/mod/github.com/distribworks/dkron/v3@v3.0.4/dkron/job.go:239 +0x2ba
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: github.com/robfig/cron/v3.(*Cron).startJob.func1(0xc00036be00, 0x37cde00, 0xc0034ad980)
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x61
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: created by github.com/robfig/cron/v3.(*Cron).startJob
Jul 22 03:30:14 myhost006 run-dkron.sh[26370]: /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x73
Jul 22 03:30:44 myhost006 systemd[1]: dkron.service holdoff time over, scheduling restart.
Jul 22 03:30:44 myhost006 systemd[1]: Stopped Dkron Agent.
Jul 22 03:30:44 myhost006 systemd[1]: Started Dkron Agent.
...
```

**Comment by sysadmind** [comment] 2020-07-22 20:21
I can confirm that we hit this about once every 24 hours in a cluster of 3 dkron servers with about 700 jobs . A huge downside to the failover is that any jobs that were scheduled to run with an `@every $time` type of schedule will not fire at that interval, but instead the timer to run those jobs will reset, potentially causing long delays in a job run. The panic stack trace looks very much like the one @drauschenbach posted above.

**Comment by victorcoder** [comment] 2020-09-03 16:28
Thanks @clarifysky for the report, we'll go with the PR the graph makes sense although I never experienced the issue.

@sysadmind Yes, the culprit of the `@every` notation will always be there in case of failover.

@drauschenbach your issue seems not related to this but more related with system resources, can you open an new issue with it?

**Comment by victorcoder** [comment] 2020-09-03 16:29
Fixed in https://github.com/distribworks/dkron/pull/799

**Closed by victorcoder** 2020-09-03 16:29 UTC
Labels: bug
