### ISSUE TITLE
After update to 3.1.4 dashboard is not working

### ISSUE THREAD

**Issue by beinbliss** [distribworks/dkron#899] opened 2021-02-03 16:29 UTC
**Describe the bug**
Updated from 3.0.8 to 3.1.4 and getting "404 not found" while accessing dashboard

**To Reproduce**
1. Update to 3.1.4
2. Execute: 
```
curl -L http://localhost:8888/dashboard
404 page not found
```

**Expected behavior**
Dashboard should work

** Specifications:**
 - OS: Linux Debian
 - Version 9

**Additional context**
Port is up and dkron is listening. Also executing `curl http://localhost:8888/v1/` works as expected

**Comment by yvanoers** [comment] 2021-02-03 20:50
Looks like a dupe of #895 .
The new UI is at `/ui`.

**Comment by victorcoder** [comment] 2021-02-03 20:52
Yes, thanks @yvanoers

**Closed by victorcoder** 2021-02-03 20:52 UTC
