### ISSUE TITLE
UI does not display correct enable/disable icon after a click; page reload usually required

### ISSUE THREAD

**Issue by drauschenbach** [distribworks/dkron#734] opened 2020-04-23 00:13 UTC
**Describe the bug**
After enabling a job, or disabling a job, the icon usually fails to change. This causes our users to typically click a 2nd time, which is obviously a mistake.

**To Reproduce**
1. Open a list of many jobs
2. Click on the pause icon of one of them, to toggle its enable status
3. Observe that the enabled icon does not change
4. Reload the page
5. Observe that the enabled icon has now changed

**Expected behavior**
After clicking the pause icon, the UI should accurately display the change that happened on the server cluster, without having to resort to a page reload.

**Specifications:**
 - Server OS: linux
 - Version 2.2.0 Pro
 - Browser OS: Windows
 - Browser: Chrome

**Additional context**
This behavior occurs on a 3-node cluster.

**Comment by victorcoder** [comment] 2020-04-23 08:55
What browser are you using? I'm unable to reproduce this using chrome. Does it work for you here http://test.dkron.io:8080/dashboard/jobs ?

**Comment by drauschenbach** [comment] 2020-04-23 14:23
No it does not work for me using the link you provided above.

1. I click on the enable/disable pause icon for the first job `10-min-shell-success`
2. The Status icon does not change
3. The banner status message momentarily appears
4. I perform a page reload
5. The Status icon has now finally changed to disabled

This time testing using Safari from my Mac with no VPN or any unusual networking. Also just tested using Chrome from my Mac with same negative result.

**Comment by drauschenbach** [comment] 2020-04-23 14:27
This is interesting. In Safari I opened the JavaScript console and the Networking tabs to watch the long-running xhr download, and after I click the enable icon the xhr is not interrupted and continues to stay connected, and this time the icon changes right away.

So if I have the developer tools open it starts working.

**Comment by drauschenbach** [comment] 2020-04-23 14:28
And now I've closed the developer tools, relaunched the Safari browser, and tested again and it is once again not working.

**Comment by victorcoder** [comment] 2020-05-05 16:22
FTR Adding this to the roadmap for improvement

**Comment by victorcoder** [comment] 2020-05-09 17:03
Unable to reproduce using Safari, Brave, Chrome, on Mac, can you try to install a fresh new browser like Brave and try it out?

Closing at the moment, feel free to reopen in case it doesn't not work.

**Closed by victorcoder** 2020-05-09 17:03 UTC
Labels: enhancement
