### ISSUE TITLE
Infinite leadership election brokes job creating

### ISSUE THREAD

**Issue by m-onyshchuk** [distribworks/dkron#1214] opened 2022-10-26 11:45 UTC
**Describe the bug**
I want to save jobs list after containers restart. Single node version like this:
```
sudo docker run -p 8080:8080 \
--name dkron-test \
-v ~/dkron.data:/dkron.data \
dkron/dkron \
agent --server --data-dir=/dkron.data \
--bootstrap-expect=1 --node-name foo \
--log-level=debug
```
works fine. Next I try to run small two nodes cluster and create job. 

**To Reproduce**
I modified docker-compose.yml from master branch:
```
version: "3"
services:
  node1:
    image: dkron/dkron
    container_name: node1
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    command: agent --server --bootstrap-expect=1 --data-dir=/dkron.data --node-name node1 --log-level=debug
    volumes:
      - ./dkron-node1.data:/dkron.data
  node2:
    image: dkron/dkron
    container_name: node2
    ports:
      - "8946"
      - "6868"
    command: agent --server --retry-join=node1:8946 --bootstrap-expect=2 --data-dir=/dkron.data --node-name node2 --log-level=debug
    volumes:
      - ./dkron-node2.data:/dkron.data
```
ran docker-compose, next ran job creating:
```
curl -i -d '{"name": "job1","schedule": "@every 10m"}' -H "Content-Type: application/json" -X POST http://localhost:8080/v1/jobs
```
and had got:
```
HTTP/1.1 500 Internal Server Error
X-Whom: node1
```
docker logs snippet:
```
node1    | time="2022-10-26T10:22:46Z" level=info msg="2022-10-26T10:22:46.717Z [ERROR] raft: failed to make requestVote RPC: target=\"{Voter node2 172.18.0.2:6868}\" error=\"dial tcp 172.18.0.2:6868: i/o timeout\" term=391"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.059Z [ERROR] raft: failed to make requestVote RPC: target=\"{Voter node1 172.18.0.3:6868}\" error=\"dial tcp 172.18.0.3:6868: i/o timeout\" term=373"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.518Z [WARN]  raft: Election timeout reached, restarting election"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.518Z [INFO]  raft: entering candidate state: node=\"Node at 172.19.0.3:6868 [Candidate]\" term=411"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.529Z [DEBUG] raft: asking for vote: term=411 from=node2 address=172.18.0.2:6868"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.529Z [DEBUG] raft: voting for self: term=411 id=node1"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.532Z [DEBUG] raft: calculated votes needed: needed=2 term=411"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.532Z [DEBUG] raft: vote granted: from=node1 term=411 tally=1"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.641Z [WARN]  raft: Election timeout reached, restarting election"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.641Z [INFO]  raft: entering candidate state: node=\"Node at 172.19.0.2:6868 [Candidate]\" term=393"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.642Z [DEBUG] raft: voting for self: term=393 id=node2"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.644Z [DEBUG] raft: asking for vote: term=393 from=node1 address=172.18.0.3:6868"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.644Z [DEBUG] raft: calculated votes needed: needed=2 term=393"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.644Z [DEBUG] raft: vote granted: from=node2 term=393 tally=1"
node1    | time="2022-10-26T10:22:48Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=SetJob node=node1 server_addr=
node1    | time="2022-10-26T10:22:48Z" level=info msg="[GIN] 2022/10/26 - 10:22:48 | 500 | 10.001947762s |      172.19.0.1 | POST     \"/v1/jobs\"" node=node1
```

**Expected behavior**
I think that 500 error is unexpected behavior

**Additional context**
Infinite leadership election as 500 error reason is only my hypothesis. May be my docker-compose.yml is wrong and i will be grateful any suggestions to fix it.

**Comment by vcastellm** [comment] 2022-10-26 15:46
Try with `bootstrap-expect=2` in both

**Comment by m-onyshchuk** [comment] 2022-10-26 16:22
I tried it, the result is the same.

**Comment by m-onyshchuk** [comment] 2022-10-26 16:31
No, previous attempt was without dir clearn up.  
Now I have cleaned dir and reran composition.
Election racing stopped. 
But POST /v1/jobs return 500 response as before.
New logs: 

```
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.927Z [INFO]  raft: election won: term=2 tally=2"
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.927Z [INFO]  raft: entering leader state: leader=\"Node at 172.19.0.2:6868 [Leader]\""
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.927Z [INFO]  raft: added peer, starting replication: peer=node1"
node2    | time="2022-10-26T16:25:15Z" level=info msg="dkron: cluster leadership acquired" node=node2
node2    | time="2022-10-26T16:25:15Z" level=info msg="dkron: monitoring leadership" node=node2
node1    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.928Z [WARN]  raft: failed to get previous log: previous-index=1 last-index=0 error=\"log not found\""
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.928Z [WARN]  raft: appendEntries rejected, sending older logs: peer=\"{Voter node1 172.19.0.3:6868}\" next=1"
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.929Z [INFO]  raft: pipelining replication: peer=\"{Voter node1 172.19.0.3:6868}\""
node2    | time="2022-10-26T16:25:15Z" level=info msg="agent: Starting scheduler" node=node2
node2    | time="2022-10-26T16:25:15Z" level=debug msg="dkron: Skipping self join check since the cluster is too small" node=node2 peer=node2
node1    | time="2022-10-26T16:25:22Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=SetJob node=node1 server_addr=
node1    | time="2022-10-26T16:25:22Z" level=info msg="[GIN] 2022/10/26 - 16:25:22 | 500 | 10.001299738s |      172.19.0.1 | POST     \"/v1/jobs\"" node=node1
```

**Comment by vcastellm** [comment] 2022-10-27 06:27
This works for me:

```
version: "3"
services:
  node1:
    image: dkron/dkron
    container_name: node1
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    command: agent --server --bootstrap-expect=1 --data-dir=/dkron.data --node-name node1 --log-level=debug
    volumes:
      - ./dkron-node1.data:/dkron.data
  node2:
    image: dkron/dkron
    container_name: node2
    ports:
      - "8946"
      - "6868"
    command: agent --server --retry-join=node1:8946 --bootstrap-expect=2 --data-dir=/dkron.data --node-name node2 --log-level=debug
    volumes:
      - ./dkron-node2.data:/dkron.data
```

After cleaning data dirs.

```
node1  | time="2022-10-27T06:26:06Z" level=info msg="dkron: cluster leadership acquired" node=node1
node1  | time="2022-10-27T06:26:06Z" level=info msg="dkron: monitoring leadership" node=node1
node1  | time="2022-10-27T06:26:06Z" level=info msg="agent: Starting scheduler" node=node1
```

**Comment by m-onyshchuk** [comment] 2022-10-27 07:05
After cleaning data dirs this works for me too. Thank you!

**Comment by m-onyshchuk** [comment] 2022-10-27 07:46
Unfortunately situation is unstable.

When I wrote that all works for me too, I have tested next order:
1) `sudo docker-compose up -d`
2) `curl -i -d '{"name": "job1","schedule": "@every 10m"}' -H "Content-Type: application/json" -X POST http://localhost:8080/v1/jobs`
3) `curl -i http://localhost:8080/v1/jobs`
Last GET shows that job1 exists
4) `sudo docker-compose down`
wait less one minute 
5) `sudo docker-compose up -d`
6) `curl -i http://localhost:8080/v1/jobs`
I have saw job1 in list and I thought that all is fine.
But sote time late I ran again:
`sudo docker-compose up -d`
`curl -i http://localhost:8080/v1/jobs`
and have saw an empty jobs array.

Now I`m testing new order:
1) remove `./dkron-node1.data` & `./dkron-node2.data` dirs
2) `sudo docker-compose up -d`
3) wait 15 seconds
4) `curl -i -d '{"name": "job1","schedule": "@every 10m"}' -H "Content-Type: application/json" -X POST http://localhost:8080/v1/jobs` 
5) wait 15 seconds
6) `curl -i http://localhost:8080/v1/jobs` (I see job1 on list)
7) `sudo docker-compose down`
8) wait 1 minute
9) `sudo docker-compose up -d`
10) `curl -i http://localhost:8080/v1/jobs` (I see an empty jobs list)

If I try to ran new order some times I can get at tenth step an empty array or array with 1 job or 500 error at fourth step.

**Comment by m-onyshchuk** [comment] 2022-10-27 11:49
I wrote a simple script (test.sh) for testing last docker-compose.yml in this topic:
```
#!/bin/bash
echo "--- test start ---"
echo ""

echo "--- clear data dirs"
rm -rf ./dkron-node1.data/
rm -rf ./dkron-node2.data/
echo "..."

echo "--- dkron cluster up - 1"
sudo docker-compose up -d
echo "..."
sleep 10

echo "--- create job1"
curl -i -d '{"name": "job1","schedule": "@every 10m"}' -H "Content-Type: application/json" -X POST http://localhost:8080/v1/jobs
echo ""
echo "..."
sleep 10

echo "--- check job1"
curl -i http://localhost:8080/v1/jobs
echo ""
echo "..."
sleep 10

echo "--- dkron cluster down - 1"
sudo docker-compose down
echo "..."

echo "--- wait 1 minute"
sleep 60

echo "--- dkron cluster up - 2"
sudo docker-compose up -d
echo "..."
sleep 10

echo "--- check job1"
curl -i http://localhost:8080/v1/jobs
echo ""
echo "..."
sleep 10

echo "--- dkron cluster down - 2"
sudo docker-compose down
echo "..."

echo "--- test finish ---"
echo ""
``` 
This script was run 10 times (`sudo ./test.sh`). Distribution of launch results:
500 error   - 1 time
job1 exists - 4 times
job1 absent - 5 times

**Comment by renom** [comment] 2022-11-24 09:27
I've tested with the script and I've got very strange results:
1. First I ran the script without modifying and got 5/5 results (job exists 5 times, job's absent 5 times)
2. Then I increased the delay before stopping the containers to 1 minute and got 0/10 results (job exists 0 times, job's absent 10 times)
I thought dkron didn't have enough time to persist the data, so I increased the delay before stopping. But the outcome worsened on the contrary. Any thoughts about the reason why did it happen?

**Comment by vcastellm** [comment] 2023-07-23 15:48
> Unfortunately situation is unstable.
> 
> When I wrote that all works for me too, I have tested next order:

This kind of report doesn't provide any clue or way to reproduce the behaviour, Dkron runs in production since a long ago and there's no reports like this one, so something must be going on on your specific setup.

Please, provide a way to reproduce or some logs that indicate what can be causing this behaviour.

Closing this in the meantime

**Closed by vcastellm** 2023-07-23 15:48 UTC
