### ISSUE TITLE
Allow more than ascii in job name and id

### ISSUE THREAD

**Issue by eylonronen** [distribworks/dkron#604] opened 2019-09-17 07:19 UTC
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
Creating jobs with utf-8 names, or names containing dots and exclamation marks

## Actual Behavior
Error code 500 from dkron

## Steps to Reproduce the Problem

  1. Try to create job with name containing dot or written in a different language from english

## Specifications

  - Version: 2.0.0-rc3
  - Platform: linux
  - Backend store: default boltDB

**Comment by yvanoers** [comment] 2019-09-17 19:52
@eylonronen the characters allowed in a job's name is intentionally limited to ensure correct internal working. For display purposes you can use the `displayname` property, which is unrestricted.

In case an incorrect name is provided, dkron should return a 400 error. If it really is a 500 as you report, I'd like to know what you are sending to dkron. Because then it is probably reporting the wrong error.

**Comment by victorcoder** [comment] 2019-10-09 19:08
Closing this because of expected behavior.

**Closed by victorcoder** 2019-10-09 19:08 UTC
