### ISSUE TITLE
Job output missing every once in a while with shell executor

### ISSUE THREAD

**Issue by zecrazytux** [distribworks/dkron#540] opened 2019-06-06 14:30 UTC
I am testing Dkron with a 3-nodes cluster baked in by and etcd cluster (same 3 nodes) and a few client agents on freshly installed VM (no real workload).

I started with a simple job definition:

```
{
  "name": "random-failure-2",
  "timezone": "Europe/Paris",
  "schedule": "@every 5s",
  "owner": "Seb",
  "owner_email": "sysadmin@afidium.com",
  "success_count": 2506,
  "error_count": 8213,
  "last_success": "2019-06-06T14:12:02.232623386Z",
  "last_error": "2019-06-06T14:12:03.536160271Z",
  "disabled": false,
  "tags": {
    "role": "web"
  },
  "retries": 0,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": null,
  "concurrency": "forbid",
  "executor": "shell",
  "executor_config": {
    "command": "bash -c 'ret=$(shuf -i0-3 -n1) && echo $ret && exit $ret'"
  },
  "status": "running",
  "next": "2019-06-06T16:12:32+02:00"
}
```

## Expected Behavior

Jobs should either be sucessful or not depending on the return code, they should however all report back their output whatever the execution state, everytime.

## Actual Behavior

Every once in a while, and that does not seem to be related to the return code / execution success or failure, the job output is missing.

on the target, the logs are sightly different (not the same order), dunno if that's related

output ok:
```
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=info msg="agent: Received event" event="query: run:job" node=web2.proto
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="agent: Running job" at=3960 node=web2.proto payload="{\"execution\":{\"job_name\":\"random-failure-2\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1559824220898507298,\"attempt\":1},\"rpc_addr\":\"192.168.10.7:6868\"}" query="run:job"
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=info msg="agent: Starting job" job=random-failure-2 node=web2.proto
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="agent: GetJob by RPC" job=random-failure-2 node=web2.proto
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="invoke: calling executor plugin" node=web2.proto plugin=shell
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="shell: going to run bash -c 'ret=$(shuf -i0-3 -n1) && echo $ret && exit $ret'" node=web2.proto subsystem_name=plugins.dkron-executor-shell
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="shell: Command output 1" node=web2.proto subsystem_name=plugins.dkron-executor-shell
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=error msg="invoke: command error output" error="exit status 1" job=random-failure-2 node=web2.proto plugin="&{0xc000096650}"
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="agent: updated peer" node=web2.proto peer="192.168.10.7:6868"
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="agent: updated peer" node=web2.proto peer="192.168.10.19:6868"
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="agent: updated peer" node=web2.proto peer="192.168.10.17:6868"
Jun  6 12:30:02 web2 dkron[10790]: time="2019-06-06T12:30:02Z" level=debug msg="invoke: Selected a server to send result" node=web2.proto server="192.168.10.19:6868"
```

output missing:

```
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="agent: Running job" at=3962 node=web2.proto payload="{\"execution\":{\"job_name\":\"random-failure-2\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1559824227372117808,\"attempt\":1},\"rpc_addr\":\"192.168.10.7:6868\"}" query="run:job"Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=info msg="agent: Starting job" job=random-failure-2 node=web2.proto
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="agent: GetJob by RPC" job=random-failure-2 node=web2.proto
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="invoke: calling executor plugin" node=web2.proto plugin=shell
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="shell: going to run bash -c 'ret=$(shuf -i0-3 -n1) && echo $ret && exit $ret'" node=web2.proto subsystem_name=plugins.dkron-executor-shell
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=error msg="invoke: command error output" error="exit status 2" job=random-failure-2 node=web2.proto plugin="&{0xc000096650}"
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="agent: updated peer" node=web2.proto peer="192.168.10.19:6868"
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="agent: updated peer" node=web2.proto peer="192.168.10.17:6868"
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="agent: updated peer" node=web2.proto peer="192.168.10.7:6868"Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="invoke: Selected a server to send result" node=web2.proto server="192.168.10.19:6868"
Jun  6 12:30:08 web2 dkron[10790]: time="2019-06-06T12:30:08Z" level=debug msg="shell: Command output 2" node=web2.proto subsystem_name=plugins.dkron-executor-shell
```

## Steps to Reproduce the Problem

  1. setup dkron cluster with etcd
  2. add the job described in this ticket

## Specifications

  - Version: 1.2.4
  - Platform: debian 8
  - Backend store: etcd

**Comment by genepix** [comment] 2019-06-13 12:19
I reproduce too. I think it's not related to the storage backend (etcd or consul). When a node doesn't register its execution when a job is done, there is no call made to the storage API (in my case, PUT on consul). So i'm getting at some times 2/3 well written executions in consul, but getting only http call for those nodes. I guess it has to be in the code, it's just not triggered, but again, sometimes it's working well and all executions are well stored.

**Comment by victorcoder** [comment] 2019-06-13 12:57
Hi @zecrazytux could you send the debug log of node `192.168.10.19:6868` just after the the ones you sent?

**Comment by victorcoder** [comment] 2019-06-14 08:15
@zecrazytux @genepix I detected the problem, it's a race condition in Execution saving, it only occurs when the job execution done save is faster than the execution creation and saving.

Fix is coming

**Comment by genepix** [comment] 2019-06-14 09:06
Great, thank you ! I get it, and I guess you're right because my job for testing was calling /bin/true

**Comment by victorcoder** [comment] 2019-10-09 19:10
Fixed in v2

**Closed by victorcoder** 2019-10-09 19:10 UTC
Labels: bug
