### ISSUE TITLE
Skipped jobs 

### ISSUE THREAD

**Issue by eylonronen** [distribworks/dkron#605] opened 2019-09-17 07:30 UTC
## Expected Behavior
Jobs should be executed on time without missing

## Actual Behavior
Some of our jobs skip their execution once, and are not executed again, because the "next execution time" doesn't arrive (since it's in the past) 
So far it only happens to our jobs that their schedule intervals are longer than 6 hours(I believe its a coincidence but still won't hurt to mention) 

## Steps to Reproduce the Problem

  1.create job and schedule it to run every day (@every 1440m)
  2.check the next day if it ran

## Specifications

  - Version:2.0.0-rc3
  - Platform:linux
  - Backend store: default boltDB

**Comment by victorcoder** [comment] 2019-09-17 20:40
@eylonronen could you please enable debug logs `log-level: debug` and send the relevant output of the leader node?

Why don't use `@daily` in the schedule?

**Comment by eylonronen** [comment] 2019-09-17 20:43
Sure, I'll set the log level.
About the schedule it's a bit tricky because we wrap it for our users and let them set the schedule with simplified gui, so we cant set it to @daily, because some users set it to run every 4 hours and some every 3 days, hence it's simpler to just schedule it by minutes

**Comment by yvanoers** [comment] 2019-09-17 21:19
@eylonronen 

>  the "next execution time" doesn't arrive (since it's in the past)

I suspect this is in reference to the next execution time returned by the API and then displayed in the dashboard. What the API returns as next execution time is not an exact representation of what the scheduler will be doing (we should really try and fix that).
The assumption that a schedule is missed because the next execution time was reported as being in the past (typically 01-01-0000T00:00:00Z), should not be made.

Other than that, I look forward to the logs :)
To go along with the logs, it would be helpful if you let us know which job or jobs missed their schedule, and when.

**Comment by eylonronen** [comment] 2019-09-18 05:02
All of our jobs have http executor and no processor, and their missing schedules are totally arbitrary :|

**Comment by omerl13** [comment] 2019-09-18 08:21
> @eylonronen could you please enable debug logs `log-level: debug` and send the relevant output of the leader node?
> 
> Why don't use `@daily` in the schedule?

We (I work with @eylonronen ) turned debug log on, yet no related log is written when the missing schedule occurred (only debug log written at that moment was “Skipping self join check since the cluster is too small”, while we have a single server and not a cluster, configured with ‘bootstrap-expect: 1’)

Also, it seems like the next schedule was at the wrong time. 
The job I checked runs @every 60m, the previous run was at 08:14, the missing was expected at 09:14, and the next successful run was at 10:27.

**Comment by omerl13** [comment] 2019-09-18 08:23
> @eylonronen
> 
> > the "next execution time" doesn't arrive (since it's in the past)
> 
> I suspect this is in reference to the next execution time returned by the API and then displayed in the dashboard. What the API returns as next execution time is not an exact representation of what the scheduler will be doing (we should really try and fix that).
> The assumption that a schedule is missed because the next execution time was reported as being in the past (typically 01-01-0000T00:00:00Z), should not be made.
> 
> Other than that, I look forward to the logs :)
> To go along with the logs, it would be helpful if you let us know which job or jobs missed their schedule, and when.

We checked the next exec time both in dkron dashboard and in the triggered action log (in our service). It does not seem to be a wrong representation, the service does not report any trigger at the expected time.

**Comment by eylonronen** [comment] 2019-09-18 13:11
Found the problem!
Every time a new job is created the method: "agent.Schedule" is called, calling "Scheduler.Restart", calling "Cron.Start", calling "Cron.run" which recomputes the next execution time for each job, hereby causing all jobs to be postponed every time a new job is created
Please fix this and release a new version quickly

**Comment by yvanoers** [comment] 2019-09-19 19:39
@eylonronen 
Great, that's really helpful!
FYI: It is being deliberated how to fix this - it looks like this isn't going to be a straight forward (therefore quick) fix.

**Comment by eylonronen** [comment] 2019-09-20 05:20
Thank you for informing me
If you'll manage to fix it in the weekend it will be great because we really need it by next week's start

**Comment by victorcoder** [comment] 2019-09-23 13:29
@eylonronen After reading your discovery I remembered this is by design, when using @every time is computed after every dkron restart, or as you noticed after a job create/update.

This is due to the internal implementation of the cron scheduler, and there is no easy path to fix this.

As @every implies that the timing will be always reset when restarting a dkron node, its purpose is for short interval jobs, - @every 10s, 1m... - where you don't mind to miss one execution on restart or update.

This is related to https://github.com/distribworks/dkron/issues/549 and will be fixed when the time comes to work in this issue.

My recommendation is that you try to convert your users input to a cron expression with fixed intervals. For example: @every 3h = 0 0 0/3 * * *

**Comment by omerl13** [comment] 2019-09-23 21:01
Why rescheduling all jobs instead of just scheduling the relevant updated job? It seems like the `Schedule.Restart` should not be used in this case.

**Comment by yvanoers** [comment] 2019-09-24 06:59
@omerl13 Because the current version of the `cron` package (this is actually an external dependency) only allows adding jobs. The interface does not allow for an existing job to be removed from or updated in the scheduler. With the current interface, the only resort is to stop the entire scheduler, set it up again, and start it.

And you're right, that is not ideal, and just updating the one job in the running scheduler will be part of the eventual fix.

**Comment by omerl13** [comment] 2019-09-24 19:55
@yvanoers Is it possible to reschedule the jobs using their current next execution time (when available)? If so, it might be a quick patch until the `cron` package is ready (maybe it is not even a patch, since there is no need to recalculate the time using the `schedule`, when the `next execution` is available for use, and already calculated).

**Comment by yvanoers** [comment] 2019-09-24 21:12
@omerl13 I gave your suggestion a try, but quickly ran into a cyclic import: dkron requires cron and cron would require dkron to get this to work.
This quick & dirty patch is not viable. To make this work would require replumbing the cron package, and that is more work than I care to do for a temporary solution.

**Comment by omerl13** [comment] 2019-09-25 20:30
> @omerl13 I gave your suggestion a try, but quickly ran into a cyclic import: dkron requires cron and cron would require dkron to get this to work.
> This quick & dirty patch is not viable. To make this work would require replumbing the cron package, and that is more work than I care to do for a temporary solution.

Thank you for trying. I guess we will have to wait until the `cron` package gets the desired update. We are checking rundeck in the meantime. Let us know if there is anything we can do to rush the update.

**Comment by omerl13** [comment] 2019-11-03 18:53
@victorcoder is the `enhancement` label fit the issue? I think it is a quite serious bug, since jobs will not run as scheduled using the simple schedule.

**Comment by victorcoder** [comment] 2019-11-11 13:11
@omerl13 I can label it as bug, doesn't matter, it's in top priorities

**Closed** 2019-11-16 00:24 UTC
Labels: bug

**Comment by victorcoder** [comment] 2019-11-16 09:36
@omerl13 could you give it a try and see if that solves the issue? Thanks

**Comment by omerl13** [comment] 2019-11-16 09:59
> @omerl13 I just released RC8, could you give it a try and see if that solves the issue? Thanks

Yes I will try it tomorrow, Thanks!

**Comment by omerl13** [comment] 2019-11-17 08:45
@victorcoder seems like it was solved, thanks!

**Comment by agarwal-nitesh** [comment] 2019-11-17 17:56
A job once marked as `partially failed` is not picked for the next run and so miss all consequent runs. I am using the RC8 version of the dkron with Redis backend.

**Comment by agarwal-nitesh** [comment] 2019-11-17 19:50
A job once marked as `partially failed` is not picked for the next run and so miss all subsequent runs. Also when a job is run manually using the play button on the dkron dashboard the next run time it picks is the current time (I have been using @every construct of the cronspec). I am using the RC9 version of the dkron with Redis backend.

**Comment by victorcoder** [comment] 2019-11-17 22:02
Please @agarwal-nitesh open a new issue for that.
