### ISSUE TITLE
Job POST return 404 error

### ISSUE THREAD

**Issue by irongomme** [distribworks/dkron#937] opened 2021-04-06 10:16 UTC
**Describe the bug**
When I want to launch manually a job with API (and therefore with UI too), I've got a succefull tooltip in UI, but a 404 return code for request. I've tried with Postman too, and it's the same !

**To Reproduce**
1. Go to /ui/#/jobs/my-job/show
2. Click on Run
3. See error in the browser debug toolbar

**Expected behavior**
A 200 return code, with information about the execution

** Specifications:**
 - OS: OpenSuse tumbleweed & Debian 10
 - dkron 3.1.6

**Comment by yvanoers** [comment] 2021-04-06 15:14
I suspect there's something missing in the reproduction steps.
Doing this as described I get a 200 as expected.
Can you clear your browser cache (I've seen inconsistent behavior because of this) and retry?
If the error occurs, please post the job configuration so we can try and reproduce this using that job. Any relevant log snippets are also appreciated!

**Comment by irongomme** [comment] 2021-04-07 10:35
I'v cleared my cache and tryed on another browser, and also in Postman ... always 404 not found api response
I've checked folder log access, removed all optionals configs (executor, tags, etc...), and still 404 not found
 
I've got this job config  : 

```
{
   "id":"purge-notifications",
   "name":"purge-notifications",
   "displayname":"Purge des notifications obsolètes",
   "timezone":"Europe/Paris",
   "schedule":"@daily",
   "owner":"ING",
   "owner_email":"dev@XXX.YY",
   "success_count":13,
   "error_count":3,
   "disabled":false,
   "tags":{
      "role":"system"
   },
   "metadata":null,
   "retries":0,
   "dependent_jobs":null,
   "parent_job":"",
   "processors":{
      "files":{
         "log_dir":"/home/deving/.dkron/logs"
      }
   },
   "concurrency":"forbid",
   "executor":"shell",
   "executor_config":{
      "command":"/data/www/imprimerie-europeenne.com/api/current/bin/cake notifications_purge"
   }
}
```

**Comment by yvanoers** [comment] 2021-04-13 21:20
Please have a look at Dkron's logging, it should give you a clue as to what is wrong.

Using this job config, I get a 404 as well. My logs says:
`ERRO[2021-04-13T23:08:23+02:00] grpc: Error calling gRPC method               error="rpc error: code = Unknown desc = no target nodes found to run job purge-notifications" method=RunJob ...`

The reason on my system is that my Dkron server does not have a tag "role" with value "system". You could have the same problem, but I can't be sure given the information currently available.

**Comment by irongomme** [comment] 2021-04-15 09:29
Yes you're right ! This is the tag wich make response to 404.  I've removed it and now I've got a 200 Ok.
But I was not able to edit my Job to remove tag, edit didn't have any effect. So I've deleted the Job to recreate it .... strange !

**Comment by yvanoers** [comment] 2021-05-01 19:24
Ok, great!

> But I was not able to edit my Job

Did you edit in the UI or using the REST API?

**Comment by irongomme** [comment] 2021-05-01 20:33
In the UI, not tryed with REST. I'll try and make a feedback.

**Comment by victorcoder** [comment] 2021-05-13 20:17
I guess we can close this, feel free to open a new bug in case tag edit doesn't work. Thanks for the support @yvanoers

**Closed by victorcoder** 2021-05-13 20:17 UTC
