### ISSUE TITLE
DKron Zookeeper Failover not working

### ISSUE THREAD

**Issue by hemantb** [distribworks/dkron#70] opened 2016-01-11 21:34 UTC
When we use multiple backend-machine to provide multiple instances of Zookeeper nodes to startup DKron and then if the ZK node to which the dkron server is connected to dies, the DKron server also dies and does not failover to the other ZK nodes

**Comment by victorcoder** [comment] 2016-01-21 11:54
@hemantb this is the expected behaviour, Dkron uses libkv to abstract the backend store and don't support listening for zookeeper events.

In case the store died, we want Dkron to die also because the server side can't not work without backend.

I'm not saying that that it's not going to be fixed at some point but not for now.

I leave the issue open meanwhile.

**Comment by victorcoder** [comment] 2019-07-31 21:07
Won't fix

**Closed by victorcoder** 2019-07-31 21:07 UTC
Labels: enhancement
