### ISSUE TITLE
Failed jobs count increasing with new jobs added - v2.0.0-b5

### ISSUE THREAD

**Issue by viperfx** [distribworks/dkron#576] opened 2019-07-19 14:59 UTC
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
When adding jobs, if they have not run yet, **should not increase** failed jobs count

## Actual Behavior
For each new job added, it increases failed job count 

## Steps to Reproduce the Problem

  1. Add a job via API
  2. Failed job count increases

## Specifications

  - Version:v2.0.0-b5
  - Platform:linux
  - Backend store:default

**Comment by yvanoers** [comment] 2019-07-19 19:57
Hi @viperfx,
I have tried to reproduce this with v2.x HEAD and v2.0.0-b5, but in both cases when adding jobs the failed count stays 0. Is there a specific place you're looking?
Can you double-check the dkron version?

**Comment by viperfx** [comment] 2019-07-19 20:01
I can provide something better - a screenshot!

<img width="1083" alt="Screen Shot 2019-07-19 at 4 00 44 PM" src="https://user-images.githubusercontent.com/328257/61562050-70e10480-aa3e-11e9-8f49-2a133e1aa317.png">

**Comment by viperfx** [comment] 2019-07-20 02:12
@yvanoers let me know if you need anything else

**Comment by yvanoers** [comment] 2019-07-20 18:54
@viperfx, the new-jobs-counting-as-failed bug was a front end (javascript) issue.
Can we rule out any kind of caching issue?

**Comment by viperfx** [comment] 2019-07-20 18:58
@yvanoers I just force reloaded and also opened DevTools on Chrome and ticked disable cache for the page and reloaded. The same numbers show up. 

Is there any other way to rule out caching? 

I can delete all the jobs and recreate them. (they are not currently being used in production)

**Comment by yvanoers** [comment] 2019-07-20 19:09
Another possibility would be having a caching proxy in between the browser and dkron, but I'd be surprised if your setup has that.

If you could recreate all jobs, please! It would be interesting to know whether the very first job added already registers as failed, or that at a certain number they start getting registered as failed. This may give me a way to reproduce the issue.

**Comment by viperfx** [comment] 2019-07-20 20:01
So another issue popped up:

I am deleting these tasks in a sequence. 

```
    def _delete_all_tasks(self):
        self._consumer = BlockingConsumer()
        jobs = self._consumer.send(
            "GET", f"{self.base_url}/jobs/", None, self.headers
        ).json()
        for job in jobs:
            self._consumer.send(
                "DELETE", f"{self.base_url}/jobs/{job['name']}/", None, self.headers
            )
```

Very simple loop. When I run the function, it seems to hang. When I check the server, the counts show 0. 

However, the API won't accept anymore jobs (if you send a request, its waiting for a response indefinitely)

I also see this stacktrace in the logs


```
badger 2019/07/20 19:52:48 INFO: Writes flushed. Stopping compactions now...
badger 2019/07/20 19:52:48 DEBUG: Flushing memtable
badger 2019/07/20 19:52:48 DEBUG: Storing value log head: {Fid:0 Len:45 Offset:2105624}
badger 2019/07/20 19:52:48 INFO: Got compaction priority: {level:0 score:1.74 dropPrefix:[109 101 109 98 101 114 95 116 97 115 107 95 106 97 112 116 99 51 95 53 48 51 51]}
badger 2019/07/20 19:52:48 INFO: Running for level: 0
badger 2019/07/20 19:52:48 DEBUG: LOG Compact. Added 2388 keys. Skipped 30 keys. Iteration took: 2.68282ms
badger 2019/07/20 19:52:48 WARNING: LOG Compact FAILED with error: Writes are blocked, possibly due to DropAll or Close
github.com/dgraph-io/badger.init.ializers
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/errors.go:113
runtime.main
        /usr/local/go/src/runtime/proc.go:188
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
failed to push discard stats to write channel
github.com/dgraph-io/badger.(*valueLog).flushDiscardStats
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/value.go:1405
github.com/dgraph-io/badger.(*valueLog).updateDiscardStats
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/value.go:1386
github.com/dgraph-io/badger.(*levelsController).compactBuildTables
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:623
github.com/dgraph-io/badger.(*levelsController).runCompactDef
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:764
github.com/dgraph-io/badger.(*levelsController).doCompact
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:833
github.com/dgraph-io/badger.(*levelsController).dropPrefix
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:281
github.com/dgraph-io/badger.(*DB).DropPrefix
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/db.go:1420
github.com/distribworks/dkron/dkron.(*Store).DeleteExecutions
        /dkron/dkron/store.go:614
github.com/distribworks/dkron/dkron.(*Store).DeleteJob.func1
        /dkron/dkron/store.go:406
github.com/dgraph-io/badger.(*DB).Update
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/txn.go:696
github.com/distribworks/dkron/dkron.(*Store).DeleteJob
        /dkron/dkron/store.go:381
github.com/distribworks/dkron/dkron.(*dkronFSM).applyDeleteJob
        /dkron/dkron/fsm.go:79
github.com/distribworks/dkron/dkron.(*dkronFSM).Apply
        /dkron/dkron/fsm.go:52
github.com/hashicorp/raft.(*Raft).runFSM.func1
        /go/pkg/mod/github.com/hashicorp/raft@v1.0.1/fsm.go:57
github.com/hashicorp/raft.(*Raft).runFSM
        /go/pkg/mod/github.com/hashicorp/raft@v1.0.1/fsm.go:120
github.com/hashicorp/raft.(*raftState).goFunc.func1
        /go/pkg/mod/github.com/hashicorp/raft@v1.0.1/state.go:146
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
failed to update discard stats
github.com/dgraph-io/badger.(*levelsController).compactBuildTables
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:624
github.com/dgraph-io/badger.(*levelsController).runCompactDef
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:764
github.com/dgraph-io/badger.(*levelsController).doCompact
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:833
github.com/dgraph-io/badger.(*levelsController).dropPrefix
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:281
github.com/dgraph-io/badger.(*DB).DropPrefix
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/db.go:1420
github.com/distribworks/dkron/dkron.(*Store).DeleteExecutions
        /dkron/dkron/store.go:614
github.com/distribworks/dkron/dkron.(*Store).DeleteJob.func1
        /dkron/dkron/store.go:406
github.com/dgraph-io/badger.(*DB).Update
        /go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/txn.go:696
github.com/distribworks/dkron/dkron.(*Store).DeleteJob
        /dkron/dkron/store.go:381
github.com/distribworks/dkron/dkron.(*dkronFSM).applyDeleteJob
        /dkron/dkron/fsm.go:79
github.com/distribworks/dkron/dkron.(*dkronFSM).Apply
        /dkron/dkron/fsm.go:52
github.com/hashicorp/raft.(*Raft).runFSM.func1
        /go/pkg/mod/github.com/hashicorp/raft@v1.0.1/fsm.go:57
github.com/hashicorp/raft.(*Raft).runFSM
        /go/pkg/mod/github.com/hashicorp/raft@v1.0.1/fsm.go:120
github.com/hashicorp/raft.(*raftState).goFunc.func1
        /go/pkg/mod/github.com/hashicorp/raft@v1.0.1/state.go:146
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337: {elog:0xc0098b2000 thisLevel:0xc000425680 nextLevel:0xc0004256e0 top:[0xc0003043c0 0xc0000fe000 0xc0000fe1e0 0xc0000fe3c0 0xc000304690 0xc000304780 0xc000304870 0xc0000fe4b0 0xc000304960 0xc0003042d0] bot:[0xc0000fe2d0] thisRange:{left:[] right:[] inf:true} nextRange:{left:[33 98 97 100 103 101 114 33 104 101 97 100 0 0 0 0 0 0 0 0] right:[106 111 98 115 47 114 101 112 111 114 116 95 116 97 115 107 95 122 122 98 52 118 100 255 255 255 255 255 255 255 255] inf:false} thisSize:0 dropPrefix:[109 101 109 98 101 114 95 116 97 115 107 95 106 97 112 116 99 51 95 53 48 51 51]}
badger 2019/07/20 19:52:48 WARNING: While compacting level 0: failed to update discard stats: failed to push discard stats to write channel: Writes are blocked, possibly due to DropAll or Close
badger 2019/07/20 19:52:48 INFO: DropPrefix done
badger 2019/07/20 19:52:48 INFO: Resuming writes
badger 2019/07/20 19:52:48 INFO: DropPrefix called on 00000000  6d 65 6d 62 65 72 5f 74  61 73 6b 5f 6a 61 70 74  |member_task_japt|
00000010  63 33 5f 35 30 33 34                              |c3_5034|
. Blocking writes...
badger 2019/07/20 19:52:48 INFO: Writes flushed. Stopping compactions now...
badger 2019/07/20 19:52:48 DEBUG: Flushing memtable
badger 2019/07/20 19:52:48 DEBUG: Storing value log head: {Fid:0 Len:45 Offset:2105727}
``` 

Is there a way to delete the DB? or a command I can run to reset everything?

**Comment by viperfx** [comment] 2019-07-20 20:02
@yvanoers is there a command I can run to delete the DB or reset the data?

**Comment by yvanoers** [comment] 2019-07-20 20:29
@viperfx well, a very crude way of getting rid of everything in a single-instance setup like this is to stop dkron and just `rm -r path/to/dkron.data/`.

Maybe @victorcoder wants to have a closer look at the write lock you got. In that case it should become a separate issue. I'm going to leave it be for now, though.

**Comment by viperfx** [comment] 2019-07-20 20:45
@yvanoers do you know the default data location?

**Comment by yvanoers** [comment] 2019-07-20 20:56
@viperfx the default is "dkron.data". This is a relative path, so that means it will create that directory in the path dkron was started.

**Comment by viperfx** [comment] 2019-07-20 21:02
@yvanoers just wanted to confirm that with just 1 API request I am able to reproduce it.

<img width="871" alt="Screen Shot 2019-07-20 at 5 01 27 PM" src="https://user-images.githubusercontent.com/328257/61584080-2039dc00-ab10-11e9-9722-18f6aa619538.png">

**Comment by yvanoers** [comment] 2019-07-20 21:16
@viperfx Okaaay...
What does the job you are creating look like?
Which package from the [release page](https://github.com/distribworks/dkron/releases) are you using?
What linux distribution are you using (this shouldn't matter much, but still)?
Is there anything specific in your setup you can think of that might be significant? (to try and minimize the variables)

**Comment by viperfx** [comment] 2019-07-20 21:25
Job Payload.

```
{
	"name": "member_task_299",
	"timezone": "UTC",
	"schedule": "* * * * *",
	"disabled": true,
	"executor": "http",
	"executor_config": {
		"body": "{\"args\": [226, \"29:1EhgOmc9SL8gDOPxYHiEurgiUe6EFnoH6R88ZtndyblnassyOBDmFTD2dQtpEfBsEvzI0SeGzCXzLXYAZqdj0kw\", \"Terence Hong\"]}",
		"debug": "true",
		"expectCode": "200",
		"headers": "[\"Content-Type: application/json\"]",
		"method": "POST",
		"timeout": "30",
		"url": "https://scrumgenius.ngrok.io/webhook/dkron_events/"
	}
}
```

Version:v2.0.0-b5
Package dkron_2.0.0-b5_linux_amd64.tar.gz
Platform:linux
Backend store:default

Setup is a typical Ubuntu EC2 Box. I can't think of anything else.

**Comment by viperfx** [comment] 2019-07-20 21:26
@yvanoers I will give it a try locally on my macbook

**Comment by yvanoers** [comment] 2019-07-20 22:12
@viperfx With that exact payload and package, still works as expected.
I am curious about what will happen on your macbook!
Also curious: which timezone is the EC2 box set to?

Could you have a look at the dashboard.js file that your faulty setup returns? I'm especially interested in the updateGraph function, which should be at or around line 373. Look for this:
`  $scope.updateGraph = function (data) {`
If you could paste the body of that function, we can definitively rule out any caching issue: depending on how the EC2 instance is accessed, some load balancer or whatever may be inbetween.

If that checks out, I'd like to investigate the values returned by dkron that get processed by that function. Are you able to do some javascript debugging?

**Comment by viperfx** [comment] 2019-07-20 22:24
```
$ timedatectl
      Local time: Sat 2019-07-20 22:21:38 UTC
  Universal time: Sat 2019-07-20 22:21:38 UTC
        RTC time: Sat 2019-07-20 22:18:50
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

@yvanoers do you know the default path for the dashboard.js file?

**Comment by viperfx** [comment] 2019-07-20 22:34
@yvanoers Oh you don't mean on the server, you mean on the browser. Yep let me check now. 

And yes, I can do some JS debugging

**Comment by viperfx** [comment] 2019-07-20 22:38
Here is the function

```
 $scope.updateGraph = function (data) {
    var gdata = $scope.series[0].data;
    var name = $scope.series[0].name;
    var color = $scope.series[0].color;
    var success_count = 0;
    var error_count = 0;
    var running = 0;

    $scope.jobs = data;
    $scope.failed_jobs = 0;
    $scope.successful_jobs = 0;

    for (i = 0; i < data.length; i++) {
      success_count = success_count + data[i].success_count;
      error_count = error_count + data[i].error_count;

      var lastErrorDate = new Date(Date.parse(data[i].last_error));
      if (new Date(Date.parse(data[i].last_success)) > lastErrorDate) {
        $scope.successful_jobs = $scope.successful_jobs + 1;
      } else if (lastErrorDate.getFullYear() !== 1) {
        $scope.failed_jobs = $scope.failed_jobs + 1;
      }

      if (data[i].status == 'running') {
        running = running + 1;
      }
    }
    $scope.success_count = success_count;

    gdata.push({ x: gdata[gdata.length - 1].x + 1, y: running })

    $scope.series[0] = {
      name: name,
      color: color,
      data: gdata
    };

    $scope.error_count = error_count;
  }
```

**Comment by yvanoers** [comment] 2019-07-21 06:07
Thanks @viperfx!
This is the proper code, so no caching issue. Good!

The dashboard regularly calls back to dkron to get the latest statusses. The response goes through this function and it determines whether or not it should report a job as failed or not.
From the point that dkron has no jobs, add one. Then I'd like to know what the response is to the request the dashboard does, and while processing that request, what the value is of `lastErrorDate` in the `updateGraph` function.
Could you try to retrieve those?

**Comment by viperfx** [comment] 2019-07-21 06:22
The `lastErrorDate` is Sun Dec 31 0000 18:42:28 GMT-0517 (Eastern Standard Time)

**Comment by viperfx** [comment] 2019-07-21 06:22
@yvanoers do you just need the one value?

**Comment by viperfx** [comment] 2019-07-21 06:34
@yvanoers to aid in debugging 

`data[i].last_error` is `0001-01-01T00:00:00Z`
`data[i].last_success` is the same value as above.

`Date.parse(data[i].last_error)` is `-62135596800000`

**Comment by viperfx** [comment] 2019-07-21 06:36
If I comment out all this date based logic, the counter is fixed.

**Comment by yvanoers** [comment] 2019-07-21 17:57
> The `lastErrorDate` is Sun Dec 31 0000 18:42:28 GMT-0517 (Eastern Standard Time)

Yep, this will trigger the problem.
I will create a proper fix to deal with jobs that haven't run yet.

Thanks for helping track this down, @viperfx!

**Comment by victorcoder** [comment] 2019-07-22 15:50
Thanks for the debugging @yvanoers and @viperfx!

@yvanoers I'm curious why you can't reproduce it for a new @job.
---

@viperfx, yes, to remove all data the most straightforward is to remove the data files in the data directory.

That write lock is indeed an issue on its own. It seems It comes from deleting all executions for the jobs, when `DeletePrefix` is called. I'll investigate.

**Comment by yvanoers** [comment] 2019-07-22 19:04
@victorcoder  I couldn't reproduce it because I failed to consider the timezone of the machine running the browser. I can reproduce it now, by setting my timezone to somewhere west of UTC, such as @viperfx's -0400.

**Comment by victorcoder** [comment] 2019-09-08 23:14
Fixed in #579

**Closed by victorcoder** 2019-09-08 23:14 UTC

**Comment by yvanoers** [comment] 2019-09-13 19:56
@viperfx you have got to be kidding me.

I fired up a VM, set the timezone to America/Toronto, started 2.0.0-rc3 and added a job as posted in this issue. Both failed count and success count remain zero.
A job that has not run yet now returns `null` for `last_success` and `last_error`. The dashboard logic discards null values from failed jobs.

Did you already investigate a bit? If not, could you trace to that same javascript function as before and share what you find?

**Comment by viperfx** [comment] 2019-09-13 20:49
@yvanoers I have not investigated but will do that now.

**Comment by viperfx** [comment] 2019-09-13 20:53
@yvanoers the issue was browser caching. I inspected the values in devtools and the code seemed the same, so did a hard refresh and it was fixed.

**Comment by yvanoers** [comment] 2019-09-13 21:06
@viperfx that's a relief!
Thanks!
